services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html:delegated
  mariadb:
    image: mariadb:latest
    volumes:
      - ../DB/pm3muenchen_de.sql:/docker-entrypoint-initdb.d/pm3muenchen_de.sql
    environment:
      MARIADB_DATABASE: pm3muenchen_de
      MARIADB_USER: pm3muenchen_de
      MARIADB_PASSWORD: Pw2cBzC8
      MARIADB_ROOT_PASSWORD: Pw2cBzC8
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb